import { UpdatePrompt } from '@/components';
import React from 'react';

export const metadata = {
	title: 'Updating Prompt - AI Prompt Sharing',
	description: 'Generated by create next app',
};

const Page = () => {
	return <UpdatePrompt />;
};

export default Page;
