import { SignIn } from '@/components';
import React from 'react';

export const metadata = {
	title: 'Signing in - AI Prompt Sharing',
	description: 'Generated by create next app',
};

const Page = () => {
	return <SignIn />;
};

export default Page;
