import { SignIn } from '@/components';
import React from 'react';

export const metadata = {
	title: 'Signing in - AI Prompt Sharing',
	description: 'Generated by create next app',
};

export default function SignInPage() {
	return <SignIn />;
}
