import '@/styles/globals.css';
import Provider from '@/components/provider/Provider';
import Nav from '@/components/shared/Nav';

export const metadata = {
	title: 'AI - Prompt Sharing',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Provider>
					<div className='main'>
						<div className='gradient' />
					</div>
					<Nav />
					<main className='app'>{children}</main>
				</Provider>
			</body>
		</html>
	);
}
