import React from 'react';
import LoadingSpinner from '@/components/shared/LoadingSpinner';

export const metadata = {
	title: 'Loading...',
	description: 'Generated by create next app',
};

export default function Loading() {
	return <LoadingSpinner />;
}
