import { MyProfile } from '@/components';
import React from 'react';

export const metadata = {
	title: 'My Profile - AI Prompt Sharing',
	description: 'Generated by create next app',
};

const Page = () => {
	return <MyProfile />;
};

export default Page;
