import { SignUp } from '@/components';
import React from 'react';

export const metadata = {
	title: 'Create an account - AI Prompt Sharing',
	description: 'Generated by create next app',
};

export default function SignUpPage() {
	return <SignUp />;
}
