import { CreatePrompt } from '@/components';
import React from 'react';

export const metadata = {
	title: 'Creating Prompt - AI Prompt Sharing',
	description: 'Generated by create next app',
};

const Page = () => {
	return <CreatePrompt />;
};

export default Page;
